import heapq, queue
import Event

class EventList:
	"""eventList : Contains all the events generated by requests in the system"""
	eventList = queue.PriorityQueue()

    #To insert the event into eventList
	def enqueueEvent(self, event):
		EventList.eventList.put((event.timestamp, event.eventType, event.eventId))

	#To get event with minimum timestamp from eventList
	def dequeueEvent(self):
		if not EventList.eventList.empty():
			tuple=EventList.eventList.get()
			event=Event.Event(tuple[0],tuple[1],tuple[2])
			return event
		else:
			pass